-- GENERATED by _scripts/build_postprints.py — do not edit by hand
return {
  ["barthelemyMMS2023"] = { slug = "crackintrati", doi = "10.1177/10812865221150771" },
  ["barthelemyIJES2021"] = { slug = "crackineo", doi = "10.1016/j.ijengsci.2021.103454" },
  ["barthelemyIJES2020_nlayersph"] = { slug = "nlayer_spheroid_conduction", doi = "10.1016/j.ijengsci.2020.103274" },
  ["barthelemyIJES2020_hilltrans"] = { slug = "transformhill", doi = "10.1016/j.ijengsci.2020.103326" },
  ["barthelemyIJES2019"] = { slug = "viscousmaxwell", doi = "10.1016/j.ijengsci.2019.05.015" },
  ["barthelemyIJSS2016"] = { slug = "viscouseshelby", doi = "10.1016/j.ijsolstr.2016.06.035" },
  ["barthelemyIJRMMS2009"] = { slug = "fracdensity", doi = "10.1016/j.ijrmms.2008.08.003" },
  ["barthelemyIJSS2009"] = { slug = "hillforcracks", doi = "10.1016/j.ijsolstr.2009.08.003" },
  ["barthelemyTIPM2009"] = { slug = "permfractures", doi = "10.1007/s11242-008-9241-9" },
}
