--- postprint-links.lua
--- Inject "open postprint" links (HTML + PDF) into the bibliography entries of the 9 articles
--- that have a self-archived postprint on this site.
---
--- Runs AFTER the `multibib` filter (see _quarto.yml). citeproc emits each reference as a
---   <div id="ref-<bibkey>" class="csl-entry">…</div>
--- We match by bib key (exact); as a fallback we match by DOI substring inside the entry text.
--- The key/DOI -> slug map lives in the sibling postprint_map.lua, regenerated by
--- _scripts/build_postprints.py — do not edit that map by hand.

local here = (PANDOC_SCRIPT_FILE or ""):gsub("[^/\\]*$", "")
local ok, map = pcall(dofile, here .. "postprint_map.lua")
if not ok or type(map) ~= "table" then
  return {}  -- map missing: do nothing rather than break the build
end

-- DOI -> entry, for the fallback match
local by_doi = {}
for _, e in pairs(map) do
  if e.doi then by_doi[e.doi:lower()] = e end
end

local function buttons(e)
  local html = table.concat({
    '<div class="pub-postprint-links">',
    '<a class="pub-postprint-link" href="/postprints/', e.slug, '/">',
    '📄 Postprint (HTML)</a>',
    '<a class="pub-postprint-link" href="/postprints/', e.slug, '/', e.slug, '.pdf">PDF</a>',
    '</div>',
  })
  return pandoc.RawBlock("html", html)
end

function Div(el)
  -- only consider citeproc reference entries
  local is_entry = el.classes:includes("csl-entry") or el.identifier:match("^ref%-")
  if not is_entry then return nil end

  local e
  local key = el.identifier:match("^ref%-(.+)$")
  if key and map[key] then
    e = map[key]
  else
    local txt = pandoc.utils.stringify(el):lower()
    for doi, entry in pairs(by_doi) do
      if txt:find(doi, 1, true) then e = entry; break end
    end
  end

  if e then
    -- Append inside the .csl-right-inline column (the text), so the buttons line up with the
    -- article description / hanging indent rather than under the [n] number. Fall back to the
    -- whole entry if that column is absent (e.g. a non-numeric CSL).
    local target = el
    for _, blk in ipairs(el.content) do
      if blk.t == "Div" and blk.classes:includes("csl-right-inline") then
        target = blk; break
      end
    end
    table.insert(target.content, buttons(e))
    return el
  end
end
