project:
  type: website

website:
  title: "JF Barthélémy"
  favicon: images/jfb.jpg
  navbar:
    right:
      - href: index.qmd
        text: Home
      # - href: files/cvjfb_en.pdf
      #   text: CV
      - href: publications.qmd
        text: Publications
      - about.qmd

# body-header: | 
#   This page brought to you by <https://example.com>

# margin-header: |
#   ![](images/jfb.jpg)

filters:
  - quarto
  - multibib
validate-yaml: false
bibliography:
  acl: _biblio/1_acl.bib
  acln: _biblio/2_acln.bib
  ascl: _biblio/3_ascl.bib
  os: _biblio/5_os.bib
  inv: _biblio/6_inv.bib
  acti: _biblio/7_acti.bib
  actn: _biblio/8_actn.bib
  com: _biblio/9_com.bib
  aff: _biblio/10_aff.bib
  rapp: _biblio/11_rapp.bib
  rappex: _biblio/12_rappex.bib
  brev: _biblio/14_brev.bib
  log: _biblio/15_log.bib
suppress-bibliography: false
link-citations: true
# csl: _biblio/elsevier-vancouver.csl
csl: https://www.zotero.org/styles/elsevier-vancouver
citeproc: false
# cite-method: biblatex

editor:
    render-on-save: true

format:
  html:
    theme:
      light: default #[_config/customjfb.scss]
      dark: superhero #[_config/customjfb-dark.scss]
    # theme: _config/customjfb.scss
    # css: _config/styles.css
    toc: true
    page-layout: full
    code-overflow: wrap

execute: 
  freeze: auto
