#!/usr/bin/env python3
"""Build the postprints section of the website from a single source of truth.

Reads _scripts/postprints_data.py and, for every entry:
  * deploys ~/articles/<dir>/Webpublish/web/  ->  postprints/<slug>/  (rendered HTML+PDF+assets ONLY,
    no sources): <slug>.html -> index.html, drops the _config/ dir (keeps only its cc-by-nc-nd.png at
    the folder root and rewrites the one reference), copies <slug>.pdf, figures/, <slug>_files/, …;
  * renders a thumbnail postprints/<slug>/thumb.png = page 1 of the PDF (PyMuPDF / fitz);
then GENERATES the derived files (never edit those by hand):
  * _includes/_postprints_cards.qmd               (card grid for postprints.qmd)
  * _includes/_postprints_featured.qmd             (featured block for publications.qmd)
  * _extensions/postprint-links/postprint_map.lua  (key/DOI -> slug map for the inline-link filter)

Run with the interpreter that has PyMuPDF, e.g.:
    ~/miniconda3/envs/fenicsx-env/bin/python _scripts/build_postprints.py
or simply `make postprints`.
"""
import os, shutil, sys

HERE = os.path.dirname(os.path.abspath(__file__))
SITE = os.path.dirname(HERE)                       # repo root (jfbarthelemy.github.io)
ARTICLES = os.path.expanduser("~/articles")
sys.path.insert(0, HERE)
from postprints_data import POSTPRINTS            # noqa: E402

try:
    import fitz  # PyMuPDF
except ImportError:
    sys.exit("PyMuPDF (fitz) is required for thumbnails — run with the fenicsx-env interpreter.")

BADGE = "cc-by-nc-nd.png"


def deploy(entry):
    slug = entry["slug"]
    src = os.path.join(ARTICLES, entry["dir"], "Webpublish", "web")
    dst = os.path.join(SITE, "postprints", slug)
    if not os.path.isdir(src):
        sys.exit(f"  ✗ missing source bundle: {src}")
    shutil.rmtree(dst, ignore_errors=True)
    os.makedirs(dst)

    for name in sorted(os.listdir(src)):
        sp = os.path.join(src, name)
        if name == "_config":
            badge = os.path.join(sp, BADGE)            # keep only the licence badge, drop sources
            if os.path.exists(badge):
                shutil.copy2(badge, os.path.join(dst, BADGE))
            continue
        if name == f"{slug}.html":
            with open(sp, encoding="utf-8") as f:
                html = f.read()
            html = html.replace(f"_config/{BADGE}", BADGE)   # badge now at folder root
            with open(os.path.join(dst, "index.html"), "w", encoding="utf-8") as f:
                f.write(html)
            continue
        (shutil.copytree if os.path.isdir(sp) else shutil.copy2)(sp, os.path.join(dst, name))

    # thumbnail = page 1 of the PDF
    pdf = os.path.join(dst, f"{slug}.pdf")
    if os.path.exists(pdf):
        doc = fitz.open(pdf)
        pix = doc[0].get_pixmap(matrix=fitz.Matrix(1.6, 1.6))
        pix.save(os.path.join(dst, "thumb.png"))
        doc.close()
    has_pdf = os.path.exists(pdf)
    print(f"  ✓ {slug:<28} -> postprints/{slug}/ (index.html, "
          f"{'pdf, ' if has_pdf else ''}thumb, assets)")
    return has_pdf


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)
    print(f"  ✓ generated {os.path.relpath(path, SITE)}")


def gen_cards(items):
    out = ["<!-- GENERATED by _scripts/build_postprints.py — do not edit by hand -->", "",
           ":::: {.grid}", ""]
    for e in items:
        s = e["slug"]
        out += [
            "::: {.g-col-12 .g-col-md-6 .g-col-lg-4}",
            "::: {.pp-card}",
            f"[![](/postprints/{s}/thumb.png){{.pp-thumb}}](/postprints/{s}/)",
            "",
            f"[{e['title']}](/postprints/{s}/){{.pp-title}}",
            "",
            f"[{e['authors']}]{{.pp-authors}}",
            "",
            f"[{e['journal']} · {e['year']}]{{.pp-badge}}",
            "",
            "::: {.pp-btns}",
            f"[{{{{< iconify mdi:web >}}}} HTML](/postprints/{s}/){{.jfb-btn .jfb-btn-outline}}",
            f"[{{{{< iconify mdi:file-pdf-box >}}}} PDF](/postprints/{s}/{s}.pdf){{.jfb-btn .jfb-btn-outline}}",
            f"[{{{{< ai doi >}}}} DOI](https://doi.org/{e['doi']}){{.jfb-btn .jfb-btn-outline}}",
            ":::",
            ":::",
            ":::",
            "",
        ]
    out += ["::::", ""]
    write(os.path.join(SITE, "_includes", "_postprints_cards.qmd"), "\n".join(out))


def gen_featured(items):
    chips = "\n".join(
        f"[{e['journal']} {e['year']}](/postprints/{e['slug']}/){{.pp-chip}}" for e in items)
    text = f"""<!-- GENERATED by _scripts/build_postprints.py — do not edit by hand -->

::: {{.pp-featured}}
##### {{{{< iconify mdi:file-document-multiple-outline >}}}} Open-access postprints

Author-accepted manuscripts of {len(items)} selected journal articles are freely available
(HTML + PDF, CC BY-NC-ND license):

::: {{.pp-chips}}
{chips}
:::

[{{{{< iconify mdi:arrow-right-circle >}}}} Browse all postprints](postprints.qmd){{.jfb-btn .jfb-btn-primary}}
:::
"""
    write(os.path.join(SITE, "_includes", "_postprints_featured.qmd"), text)


def gen_lua_map(items):
    lines = ["-- GENERATED by _scripts/build_postprints.py — do not edit by hand", "return {"]
    for e in items:
        lines.append(
            f'  ["{e["key"]}"] = {{ slug = "{e["slug"]}", doi = "{e["doi"]}" }},')
    lines += ["}", ""]
    write(os.path.join(SITE, "_extensions", "postprint-links", "postprint_map.lua"),
          "\n".join(lines))


def main():
    print("Deploying postprints:")
    for e in POSTPRINTS:
        deploy(e)
    items = sorted(POSTPRINTS, key=lambda e: e["year"], reverse=True)
    print("Generating derived files:")
    gen_cards(items)
    gen_featured(items)
    gen_lua_map(items)
    print(f"Done — {len(POSTPRINTS)} postprints.")


if __name__ == "__main__":
    main()
