#!/usr/bin/env python3
"""Build the publications timeline from `_biblio/*.bib`.

The thirteen BibLaTeX files stay the single source of truth. This script turns
them into plain-markdown Quarto includes: a chronological timeline, a statistics
strip for the home page, a short "recent work" list, and one aggregated
`files/publications.bib` for the download button.

Bibliographic data is never reformatted by hand: each file is handed to the
pandoc bundled with Quarto (`quarto pandoc -f biblatex -t csljson`), which
resolves LaTeX escapes to Unicode and normalises dates, and every field written
out comes verbatim from that conversion. The only derived values are author
initials and the section badges declared in `publications_meta.py`.

Standard library only — run it with any Python 3.9+:

    python3 _scripts/build_publications.py      (or: make publications)
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
import unicodedata
import urllib.error
import urllib.parse
import urllib.request
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from publications_meta import (  # noqa: E402
    BADGE_BY_CSL_TYPE,
    FAMILIES,
    FAMILY_ORDER,
    GROUPS,
)

ROOT = Path(__file__).resolve().parent.parent
BIBLIO = ROOT / "_biblio"
INCLUDES = ROOT / "_includes"
FILES = ROOT / "files"

# The author whose name is emphasised in every author list.
SELF_FAMILY = "barthelemy"

BANNER = "<!-- GENERATED by _scripts/build_publications.py — do not edit by hand -->"

# `--offline` skips the DOI lookups entirely and keeps every `.bib` value, for a
# run that must not touch the network.
OFFLINE = "--offline" in sys.argv


# --------------------------------------------------------------------------
# bib -> CSL JSON
# --------------------------------------------------------------------------

def csljson(bib: Path) -> list[dict]:
    """Convert one BibLaTeX file with the pandoc shipped inside Quarto."""
    proc = subprocess.run(
        ["quarto", "pandoc", "-f", "biblatex", "-t", "csljson", str(bib)],
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:
        raise SystemExit(f"pandoc failed on {bib.name}:\n{proc.stderr}")
    return json.loads(proc.stdout)


def count_bib_entries(bib: Path) -> int:
    """Count `@type{...` records, ignoring the Better BibTeX comment blocks."""
    return len(re.findall(r"^@\w+\s*\{", bib.read_text(encoding="utf-8"), re.M))


# --------------------------------------------------------------------------
# formatting helpers
# --------------------------------------------------------------------------

def deaccent(text: str) -> str:
    return "".join(
        c for c in unicodedata.normalize("NFD", text) if not unicodedata.combining(c)
    )


def initials(given: str) -> str:
    """Normalise a given name to initials.

    Zotero exported these in six different shapes — `Jean-François`, `J.-F.`,
    `J. -F.` (note the space), `A. B.`, `M L E`, `V I`. All of them must come
    out identically, or the same person reads as two.
    """
    given = re.sub(r"\s*-\s*", "-", given.strip())
    out = []
    for token in given.split():
        parts = [p for p in token.split("-") if p]
        letters = [f"{p[0].upper()}." for p in parts if p[0].isalpha()]
        if letters:
            out.append("-".join(letters))
    return " ".join(out)


def escape_md(text: str) -> str:
    """Escape the characters that would change markdown structure.

    None of the 107 current entries contains any of them; this only guards
    future additions. `\\` and `$` are deliberately left alone so that a title
    carrying inline math keeps working.
    """
    return re.sub(r"([\[\]*`])", r"\\\1", text)


def format_authors(entry: dict) -> str:
    names = []
    for person in entry.get("author", []):
        if "literal" in person:
            names.append(escape_md(person["literal"]))
            continue
        family = " ".join(
            p for p in (person.get("non-dropping-particle"), person.get("family")) if p
        )
        given = initials(person.get("given", ""))
        suffix = person.get("suffix")
        label = f"{given} {family}".strip() if given else family
        if suffix:
            label = f"{label} {suffix}"
        label = escape_md(label)
        if deaccent(person.get("family", "")).lower() == SELF_FAMILY:
            label = f"**{label}**"
        names.append(label)
    return ", ".join(names)


def format_venue(entry: dict) -> str:
    """The reference line, in the shape a reference is usually written.

    Journal articles come out as `Journal 341 (2026) 114293` — venue, volume,
    year in parentheses, pages — which is how the field writes them; the other
    kinds follow the same logic, with the year always in parentheses at the end
    of what identifies the work.
    """
    kind = entry.get("type")
    container = entry.get("container-title")
    year = issued_parts(entry)[0]
    y = f"({year})" if year else ""

    def join(*bits):
        return " ".join(str(b) for b in bits if b)

    if kind == "article-journal":
        volume = entry.get("volume")
        issue = entry.get("issue") or entry.get("number")
        vol = f"{volume}({issue})" if volume and issue else (str(volume) if volume else "")
        out = join(container, vol, y, entry.get("page"))
    elif kind == "chapter":
        head = f"In: {container}" if container else ""
        out = ", ".join(b for b in (head, entry.get("publisher")) if b)
        out = join(out, y, entry.get("page"))
    elif kind == "paper-conference":
        out = ", ".join(b for b in (container, entry.get("publisher-place")) if b)
        out = join(out, y)
    elif kind in ("report", "thesis"):
        bits = [entry.get("genre"), entry.get("publisher")]
        if kind == "report" and entry.get("number"):
            bits.append(f"no. {entry['number']}")
        out = join(", ".join(b for b in bits if b), y)
    elif kind == "patent":
        bits = [entry.get("genre")]
        if entry.get("number"):
            bits.append(f"no. {entry['number']}")
        out = join(", ".join(b for b in bits if b), y)
    elif kind == "software":
        bits = []
        version = normalize_version(entry.get("version"))
        if version:
            bits.append(f"v{version}")
        if entry.get("publisher"):
            bits.append(entry["publisher"])
        out = join(", ".join(bits), y)
    else:
        out = join(container, y)

    return escape_md(re.sub(r"\s+", " ", out).strip())


# --------------------------------------------------------------------------
# software versions: ask the DOI, not the .bib
# --------------------------------------------------------------------------
# The `.bib` files come out of Zotero and are not edited here, so their
# `version` field is a snapshot frozen at the moment the entry was exported.
# The DOI beside it is not: a Zenodo deposit has a *concept* DOI that always
# resolves to the newest release. Asking DataCite for it keeps the site correct
# with no change to the bibliography.

DATACITE = "https://api.datacite.org/dois/"
_version_cache: dict[str, str | None] = {}


def normalize_version(value) -> str | None:
    """`v0.18.0+doc1` -> `0.18.0`.

    Zenodo records whatever the release tag said. A leading `v` is noise, and
    build metadata after `+` — ChemistryLab's `+doc1` comes from a
    documentation-only re-tag — is not part of the version.
    """
    if not value:
        return None
    text = str(value).strip().lstrip("vV").split("+", 1)[0].strip()
    return text or None


def _datacite(doi: str) -> dict:
    req = urllib.request.Request(
        DATACITE + urllib.parse.quote(doi),
        headers={"User-Agent": "jfbarthelemy.github.io build_publications.py"},
    )
    with urllib.request.urlopen(req, timeout=20) as response:
        return json.load(response)["data"]["attributes"]


def live_version(doi: str) -> str | None:
    """The newest released version behind a Zenodo DOI, or None.

    If the bibliography cites a *version* DOI rather than the concept — as the
    echoes entry does — follow its `IsVersionOf` to the concept, so the answer
    is still the latest and not the version that happened to be current when
    the entry was exported.

    Any failure returns None and the caller keeps the `.bib` value: the site
    must stay buildable with no network.
    """
    if doi in _version_cache:
        return _version_cache[doi]
    result = None
    try:
        attrs = _datacite(doi)
        concept = next(
            (r.get("relatedIdentifier") for r in attrs.get("relatedIdentifiers", [])
             if r.get("relationType") == "IsVersionOf" and r.get("relatedIdentifier")),
            None,
        )
        if concept:
            attrs = _datacite(concept)
        result = normalize_version(attrs.get("version"))
    except Exception as exc:  # network down, DOI not in DataCite, malformed answer
        print(f"    ! {doi}: {type(exc).__name__} — keeping the version from the .bib")
    _version_cache[doi] = result
    return result


def issued_parts(entry: dict) -> tuple[int, int, int]:
    parts = entry.get("issued", {}).get("date-parts", [[]])[0]
    parts = list(parts) + [0, 0, 0]
    return int(parts[0]), int(parts[1] or 0), int(parts[2] or 0)


def link_label(url: str) -> str:
    host = re.sub(r"^https?://(www\.)?", "", url).split("/")[0].lower()
    if "hal" in host:
        return "HAL"
    if "zenodo" in host:
        return "Zenodo"
    if "patents.google" in host:
        return "Patent"
    if host.endswith("github.io") or "readthedocs" in host:
        return "Docs"
    return "Publisher"


# --------------------------------------------------------------------------
# collect
# --------------------------------------------------------------------------

def postprint_map() -> dict[str, dict]:
    """Reuse the postprints source of truth rather than duplicating it."""
    try:
        from postprints_data import POSTPRINTS
    except ImportError:
        print("  ! _scripts/postprints_data.py not importable — no postprint links")
        return {}
    return {p["key"]: p for p in POSTPRINTS}


def collect() -> list[dict]:
    postprints = postprint_map()
    entries: list[dict] = []
    problems: list[str] = []

    for key, filename, family, badge, section in GROUPS:
        bib = BIBLIO / filename
        if not bib.exists():
            raise SystemExit(f"missing bibliography file: {bib}")

        raw = csljson(bib)
        expected = count_bib_entries(bib)
        if len(raw) != expected:
            problems.append(
                f"{filename}: {expected} records in the file but {len(raw)} converted"
            )
        if not raw:
            problems.append(f"{filename}: no entry at all")

        for e in raw:
            year, month, day = issued_parts(e)
            if not year:
                problems.append(f"{e.get('id', '?')} ({filename}): no year")
            if not e.get("title"):
                problems.append(f"{e.get('id', '?')} ({filename}): no title")
            if not e.get("author"):
                problems.append(f"{e.get('id', '?')} ({filename}): no author")

            # Software versions come from the DOI, not from the frozen `.bib`
            # field; see `live_version` above.
            if family == "software" and e.get("DOI") and not OFFLINE:
                latest = live_version(e["DOI"])
                if latest and latest != normalize_version(e.get("version")):
                    print(f"    {e['id']}: {e.get('version')} → v{latest} (from the DOI)")
                    e["version"] = latest

            pp = postprints.get(e["id"])
            entries.append(
                {
                    "id": e["id"],
                    "group": key,
                    "family": family,
                    "section": section,
                    "badge": BADGE_BY_CSL_TYPE.get(e.get("type"), badge),
                    "year": year,
                    "sort": (year, month, day),
                    "title": escape_md(e.get("title", "")),
                    "authors": format_authors(e),
                    "venue": format_venue(e),
                    "doi": e.get("DOI"),
                    "url": e.get("URL"),
                    "postprint": pp,
                }
            )

    if problems:
        print("\nBibliography problems:", file=sys.stderr)
        for p in problems:
            print(f"  - {p}", file=sys.stderr)
        raise SystemExit("aborting: fix the bibliography before regenerating")

    entries.sort(
        key=lambda e: (-e["sort"][0], -e["sort"][1], -e["sort"][2],
                       FAMILY_ORDER[e["family"]], e["title"])
    )
    return entries


# --------------------------------------------------------------------------
# emit
# --------------------------------------------------------------------------

def render_entry(e: dict) -> list[str]:
    target = None
    if e["doi"]:
        target = f"https://doi.org/{e['doi']}"
    elif e["url"]:
        target = e["url"]

    attrs = [
        f"#ref-{e['id']}",
        ".pub-item",
        f'data-family="{e["family"]}"',
        f'data-group="{e["group"]}"',
        f'data-year="{e["year"]}"',
    ]
    if e["postprint"]:
        attrs.append('data-oa="1"')

    out = [f"::: {{{' '.join(attrs)}}}"]
    out.append("")
    if target:
        out.append(f"[{e['title']}]({target}){{.pub-title}}")
    else:
        out.append(f"[{e['title']}]{{.pub-title}}")
    out.append("")
    out.append(f"[{e['authors']}]{{.pub-authors}}")
    if e["venue"]:
        out.append("")
        out.append(f"[{e['venue']}]{{.pub-venue}}")

    out += ["", "::: {.pub-tags}",
            f"[{e['badge']}]{{.pub-tag .pub-tag-{e['family']}}}"]
    if e["postprint"]:
        out.append("[Open access]{.pub-tag .pub-tag-oa}")
    out.append(":::")

    links = []
    if e["doi"]:
        links.append(f"[DOI](https://doi.org/{e['doi']}){{.pub-link}}")
    if e["url"] and e["url"] != target:
        links.append(f"[{link_label(e['url'])}]({e['url']}){{.pub-link}}")
    elif e["url"] and not e["doi"]:
        pass  # the title already points there
    if e["postprint"]:
        slug = e["postprint"]["slug"]
        links.append(f"[Postprint](/postprints/{slug}/){{.pub-link}}")
        links.append(f"[PDF](/postprints/{slug}/{slug}.pdf){{.pub-link}}")
    if links:
        out += ["", "::: {.pub-links}", " ".join(links), ":::"]

    out += [":::", ""]
    return out


def write_timeline(entries: list[dict]) -> None:
    lines = [BANNER, "", "::::: {.pub-timeline}", ""]
    current_year = None
    for e in entries:
        if e["year"] != current_year:
            current_year = e["year"]
            lines += ["::: {.pub-year}", f"## {current_year} {{#pub-year-{current_year}}}", ":::", ""]
        lines += render_entry(e)
    lines += [":::::", ""]
    (INCLUDES / "_publications_timeline.qmd").write_text("\n".join(lines), encoding="utf-8")


def write_stats(entries: list[dict]) -> None:
    n_total = len(entries)
    n_journal = sum(1 for e in entries if e["family"] == "journal")
    n_oa = sum(1 for e in entries if e["postprint"])
    n_pkg = len([p for p in (ROOT / "software").glob("*.qmd") if p.stem != "mpcm"])

    stats = [
        (n_total, "publications"),
        (n_journal, "journal articles"),
        (n_oa, "open-access postprints"),
        (n_pkg, "software packages"),
    ]
    lines = [BANNER, "", ":::: {.stat-strip}", ""]
    for value, label in stats:
        lines += ["::: {.stat}", f"[{value}]{{.stat-value}}",
                  f"[{label}]{{.stat-label}}", ":::", ""]
    lines += ["::::", ""]
    (INCLUDES / "_publications_stats.qmd").write_text("\n".join(lines), encoding="utf-8")


def write_recent(entries: list[dict], count: int = 5) -> None:
    recent = [e for e in entries if e["family"] == "journal"][:count]
    lines = [BANNER, "", "::::: {.pub-timeline .pub-timeline-flat}", ""]
    for e in recent:
        lines += render_entry(e)
    lines += [":::::", ""]
    (INCLUDES / "_publications_recent.qmd").write_text("\n".join(lines), encoding="utf-8")


def write_bibtex() -> None:
    """Aggregate the thirteen files, dropping Better BibTeX's comment blocks."""
    FILES.mkdir(exist_ok=True)
    chunks = ["% Publications of Jean-François Barthélémy",
              "% GENERATED by _scripts/build_publications.py — do not edit by hand", ""]
    for _key, filename, _family, _badge, section in GROUPS:
        body = (BIBLIO / filename).read_text(encoding="utf-8")
        body = "\n".join(l for l in body.splitlines() if not l.lstrip().startswith("%"))
        body = re.sub(r"\n{3,}", "\n\n", body).strip()
        chunks += [f"% ===== {section} =====", "", body, ""]
    (FILES / "publications.bib").write_text("\n".join(chunks) + "\n", encoding="utf-8")


def main() -> None:
    if OFFLINE:
        print("Offline: keeping the software versions written in the .bib")
    entries = collect()
    write_timeline(entries)
    write_stats(entries)
    write_recent(entries)
    write_bibtex()

    years = sorted({e["year"] for e in entries})
    print(f"✓ {len(entries)} publications, {years[0]}–{years[-1]}")
    for family, label in FAMILIES:
        n = sum(1 for e in entries if e["family"] == family)
        print(f"    {label:<20} {n:>3}")
    print(f"    {'with a postprint':<20} {sum(1 for e in entries if e['postprint']):>3}")
    print("  wrote _includes/_publications_{timeline,stats,recent}.qmd and files/publications.bib")


if __name__ == "__main__":
    main()
