"""Single source of truth for the open-access postprints.

To add or update a postprint:
  1. (re)render the article's Quarto project so that <article>/Webpublish/web/ is up to date;
  2. add or edit ONE entry in the POSTPRINTS list below;
  3. run `make postprints` (or `_scripts/build_postprints.py`);
  4. `quarto preview` to check, then commit & push.

Every field is used:
  dir      source folder under ~/articles (its Webpublish/web/ is deployed)
  slug     public URL segment -> https://jfbarthelemy.github.io/postprints/<slug>/
  key      BibTeX cite key in _biblio/1_acl.bib (used to inject inline links on Publications)
  title    article title
  authors  short author list (as in the citation)
  journal  short journal name (shown on the card badge)
  year     publication year (cards are sorted by year, descending)
  doi      DOI (the card's DOI button -> https://doi.org/<doi>)

Derived artefacts (generated by build_postprints.py — DO NOT edit by hand):
  postprints/<slug>/                      deployed HTML+PDF+assets (+ thumb.png)
  postprints/_cards.qmd                   card grid included by postprints.qmd
  _includes/_postprints_featured.qmd      "featured" block included by publications.qmd
  _extensions/postprint-links/postprint_map.lua   key/DOI -> slug map for the Lua filter
"""

POSTPRINTS = [
    dict(
        dir="2022_CrackInTraTI", slug="crackintrati", key="barthelemyMMS2023",
        title="Compliance of a crack embedded in a transformed transversely isotropic material",
        authors="J.-F. Barthélémy, I. Sevostianov, A. Giraud, E. N. Vilchevskaya",
        journal="Math. Mech. Solids", year=2024, doi="10.1177/10812865221150771",
    ),
    dict(
        dir="2020_CrackInEO", slug="crackineo", key="barthelemyIJES2021",
        title="Micromechanical modeling of a cracked elliptically orthotropic medium",
        authors="J.-F. Barthélémy, I. Sevostianov, A. Giraud",
        journal="Int. J. Eng. Sci.", year=2021, doi="10.1016/j.ijengsci.2021.103454",
    ),
    dict(
        dir="2020_NlayerSpheroidConduction_IJES", slug="nlayer_spheroid_conduction",
        key="barthelemyIJES2020_nlayersph",
        title="The Eshelby problem of the confocal N-layer spheroid with imperfect interfaces "
              "and the notion of equivalent particle in thermal conduction",
        authors="J.-F. Barthélémy, F. Bignonnet",
        journal="Int. J. Eng. Sci.", year=2020, doi="10.1016/j.ijengsci.2020.103274",
    ),
    dict(
        dir="2020_TransformHill", slug="transformhill", key="barthelemyIJES2020_hilltrans",
        title="Simplified approach to the derivation of the relationship between Hill "
              "polarization tensors of transformed problems and applications",
        authors="J.-F. Barthélémy",
        journal="Int. J. Eng. Sci.", year=2020, doi="10.1016/j.ijengsci.2020.103326",
    ),
    dict(
        dir="2019_ViscousMaxwell", slug="viscousmaxwell", key="barthelemyIJES2019",
        title="Effective properties of ageing linear viscoelastic media with spheroidal inhomogeneities",
        authors="J.-F. Barthélémy, A. Giraud, J. Sanahuja, I. Sevostianov",
        journal="Int. J. Eng. Sci.", year=2019, doi="10.1016/j.ijengsci.2019.05.015",
    ),
    dict(
        dir="2016_ViscousEshelby", slug="viscouseshelby", key="barthelemyIJSS2016",
        title="The Eshelby inclusion problem in ageing linear viscoelasticity",
        authors="J.-F. Barthélémy, A. Giraud, F. Lavergne, J. Sanahuja",
        journal="Int. J. Solids Struct.", year=2016, doi="10.1016/j.ijsolstr.2016.06.035",
    ),
    dict(
        dir="2009_FractureDensity_IJRMMS", slug="fracdensity", key="barthelemyIJRMMS2009",
        title="Estimates of fracture density and uncertainties from well data",
        authors="J.-F. Barthélémy, M. L. E. Guiton, J.-M. Daniel",
        journal="Int. J. Rock Mech. Min. Sci.", year=2009, doi="10.1016/j.ijrmms.2008.08.003",
    ),
    dict(
        dir="2009_HillForCracks_IJSS", slug="hillforcracks", key="barthelemyIJSS2009",
        title="Compliance and Hill polarization tensor of a crack in an anisotropic matrix",
        authors="J.-F. Barthélémy",
        journal="Int. J. Solids Struct.", year=2009, doi="10.1016/j.ijsolstr.2009.08.003",
    ),
    dict(
        dir="2009_Permeabilite_TIPM", slug="permfractures", key="barthelemyTIPM2009",
        title="Effective permeability of media with a dense network of long and micro fractures",
        authors="J.-F. Barthélémy",
        journal="Transport in Porous Media", year=2008, doi="10.1007/s11242-008-9241-9",
    ),
]
